name: Scheduled jobs

on:
  schedule:
    # Every Monday at 00:00
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  hypothesis-tests:
    name: Hypothesis tests with CI profile
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install ".[tests]"
      - run: pytest -m hypothesis -m hypothesis_nested --hypothesis-profile CI test

  test-corpus-part-1:
    name: Corpus tests. Part 1
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 1
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install ".[tests]"
      # Azure.com APIs take >50% of all APIs in the test corpus
      - run: pytest test-corpus -k 'azure.com'

  test-corpus-part-2:
    name: Corpus tests. Part 2
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 1
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install ".[tests]"
      # It matches 'microsoft.com/graph/1.0.1/openapi.yaml' that has >5000 API operations.
      # Running tests only for this API takes a lot of time and worth having a separate job due to the max time limit
      - run: pytest test-corpus -k 'microsoft.com and graph'

  test-corpus-part-3:
    name: Corpus tests. Part 3
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 1
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install ".[tests]"
      # It matches all Amazon APIs
      - run: pytest test-corpus -k 'amazonaws.com'

  test-corpus-part-4:
    name: Corpus tests. Part 4
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 1
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install ".[tests]"
      # It matches all Google APIs
      - run: pytest test-corpus -k 'googleapis.com'

  test-corpus-part-5:
    name: Corpus tests. Part 5
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 1
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install ".[tests]"
      # It matches everything except that large MS API and all Azure.com | Amazon | Google APIs
      - run: pytest test-corpus -k 'not (microsoft.com and graph) and not azure.com and not amazonaws.com and not googleapis.com'
