name: Scheduled jobs

on:
  schedule:
    # Every Monday at 00:00
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  hypothesis-tests:
    name: Hypothesis tests with CI profile
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install ".[tests]"
      - run: pytest -m hypothesis -m hypothesis_nested --hypothesis-profile CI test

  test-corpus:
    name: Corpus tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 1
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install ".[tests]"
      - run: pytest test-corpus -n auto
